name: validate

on:
  pull_request:
    paths:
      - "mrj.toml"
      - ".github/workflows/validate.yml"

env:
  MRJ_VERSION: v0.1.0-alpha.10

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Install mrj
        uses: jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2 # v2.1.0
        with:
          repo: dhth/mrj
          tag: ${{ env.MRJ_VERSION }}
      - uses: actions/checkout@v4
      - name: Validate
        run: |
          mrj config validate
